language: android
before_install:
- echo "Before install stage"
install:
- echo "Install stage"
- sudo yum install -y nodejs
- sudo yum update -y
- sudo yum install -y nodejs imagemagick
- sudo npm -g install cordova cordova-gen
- sudo npm install
# before_script:
# - "gem install travis-artifacts"