language: node_js
# Installation des packages
addons:
  apt:
    packages:
    - nodejs
    - npm
before_install:
- echo "Before install stage"
- npm -g install cordova cordova-gen
- cordova platform add browser
- cordova platform add browser
install:
- echo "Install stage"
- cordova build
# before_script:
# - "gem install travis-artifacts"