language: android
addons:
  apt:
    packages:
    - nodejs
    - npm
before_install:
- echo "Before install stage"
install:
- echo "Install stage"
- npm -g install cordova cordova-gen
- npm install
# before_script:
# - "gem install travis-artifacts"